pipeline {
    agent any

    environment {
        IMAGE_A = 'adnanizco/service-a:latest'
        IMAGE_B = 'adnanizco/service-b:latest'
        REGISTRY_CREDENTIALS = 'dockerhub-credentials'
    }

    stages {
        // You can optionally skip this stage since Jenkins already clones the repo via SCM
        stage('Build Docker Images') {
            steps {
                sh 'docker build -t $IMAGE_A ./my-microservices-project/src/service-a'
                sh 'docker build -t $IMAGE_B ./my-microservices-project/src/service-b'
            }
        }

        stage('Push to DockerHub') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${REGISTRY_CREDENTIALS}", usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh '''
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $IMAGE_A
                        docker push $IMAGE_B
                    '''
                }
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f my-microservices-project/k8s/'
            }
        }
    }
}
