apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf
  template:
    metadata:
      labels:
        app: upf
    spec:
      containers:
      - name: upf
        image: open5gs/upf:latest
        ports:
        - containerPort: 2152
